[Variables]
Active=3

Open1=0
Name1=Gateway
Address1=192.168.0.1
Shortcut1=cmd.exe
ThresholdY1=10
ThresholdR1=20

Open2=0
Name2=Google
Address2=8.8.8.8
Shortcut2=
ThresholdY2=40
ThresholdR2=80

Open3=0
Name3=Cloudflare
Address3=1.1.1.1
Shortcut3=
ThresholdY3=40
ThresholdR3=80

Open4=0
Name4=Dyn
Address4=216.146.35.35
Shortcut4=
ThresholdY4=40
ThresholdR4=80

Open5=0
Name5=OpenDNS
Address5=208.67.222.222
Shortcut5=
ThresholdY5=40
ThresholdR5=80

Open6=0
Name6=Comcast
Address6=75.75.76.76
Shortcut6=
ThresholdY6=40
ThresholdR6=80

Open7=0
Name7=Verisign
Address7=64.6.64.6
Shortcut7=
ThresholdY7=40
ThresholdR7=80

Open8=0
Name8=Comodo
Address8=8.26.56.26
Shortcut8=
ThresholdY8=40
ThresholdR8=80

Open9=0
Name9=Telstra
Address9=139.130.4.5
Shortcut9=
ThresholdY9=40
ThresholdR9=80

Open10=0
Name10=Yandex
Address10=77.88.8.8
Shortcut10=
ThresholdY10=40
ThresholdR10=80
