[Rainmeter]
LocalFont="#SKINSPATH#Alex Kolstad\Variables\Fonts\Nexa Bold.otf"
LocalFont2="#SKINSPATH#Alex Kolstad\Variables\Fonts\Nexa Bold.otf"
LocalFont3="#SKINSPATH#Alex Kolstad\Variables\Fonts\Nexa Bold.otf"
LocalFont4="#SKINSPATH#Alex Kolstad\Variables\Fonts\Nexa Bold.otf"
LocalFont5="#SKINSPATH#Alex Kolstad\Variables\Fonts\Nexa Bold.otf"
LocalFont6="#SKINSPATH#Alex Kolstad\Variables\Fonts\Nexa Bold.otf"
LocalFont7="#SKINSPATH#Alex Kolstad\Variables\Fonts\Nexa Bold.otf"
